{
  lib,
  stdenvNoCC,
  fetchFromGitHub,
  callPackage,
  makeWrapper,
  installShellFiles,
  bash,
  coreutils,
  curl,
  findutils,
  git,
  gnugrep,
  gnused,
  nix-update-script,

  # vuh knows how to download and overwrite itself. That cannot work from the
  # Nix store, and it makes every invocation reach out to github once a day, so
  # it is off by default. Turning it on only re-enables the *check* (`vuh
  # --update` and the daily reminder); replacing the binary stays impossible and
  # vuh will say so.
  enableUpdateChecks ? false,
}:

let
  # Everything vuh shells out to. `curl` is only ever called by the update
  # checker, so it is only pulled in when that is enabled.
  runtimeInputs = [
    coreutils
    findutils
    git
    gnugrep
    gnused
  ]
  ++ lib.optional enableUpdateChecks curl;
in
stdenvNoCC.mkDerivation (finalAttrs: {
  pname = "vuh";
  version = "2.15.0";

  src = fetchFromGitHub {
    owner = "Greewil";
    repo = "version-update-helper";
    tag = "v${finalAttrs.version}";
    hash = "sha256-0iSv56JMT3rUmEbTkZ8Cs2h//lMeIif57cpDtV/sNu4=";
  };

  patches = [
    # vuh writes its update-check timestamp next to the installed script. The
    # store is read-only, so runtime state moves to $XDG_STATE_HOME/vuh.
    ./patches/0001-keep-mutable-state-out-of-the-install-prefix.patch
    # Whether vuh may phone home becomes an installation-time placeholder, and
    # the "download a tarball over myself" code path is removed.
    ./patches/0002-make-update-checking-a-build-time-switch.patch
    # `.vuh` project configs are sourced; reading them back from a predictable
    # path in /tmp is a local code-execution footgun (and breaks concurrent runs).
    ./patches/0003-do-not-source-a-predictable-file-in-tmp.patch
    # `vuh --help` greps its own source. $0 is the makeWrapper wrapper, which
    # does not contain the help text; ${BASH_SOURCE[0]} always does.
    ./patches/0004-read-the-help-text-from-the-script-itself.patch
    # An escaped `_` in a grep pattern makes GNU grep >= 3.8 print "stray \
    # before _" on every mono repository command.
    ./patches/0005-drop-a-pointless-backslash-from-a-grep-pattern.patch
    # With update checks enabled, the first command of the day used to abort
    # outright when github could not be reached. Being offline is not an error.
    ./patches/0006-a-failed-update-check-must-not-abort-the-command.patch
  ];

  # The substitutions upstream's installer.sh performs after copying the script
  # into place. DATA_DIR describes the installation itself, so under Nix it
  # points at the immutable copy of that information in the store.
  postPatch = ''
    substituteInPlace vuh.sh \
      --replace-fail "<should_be_replace_after_installation:DATA_DIR>" "${placeholder "out"}/share/vuh" \
      --replace-fail "<should_be_replace_after_installation:UPDATE_CHECKS>" "${lib.boolToString enableUpdateChecks}"
  '';

  strictDeps = true;

  nativeBuildInputs = [
    installShellFiles
    makeWrapper
  ];

  # So that patchShebangs resolves `#!/usr/bin/env bash` to a bash from the
  # store. It has to be this one and not `bashNonInteractive`: vuh clears and
  # re-reads its configuration variables with `compgen -v`, and bash only has
  # `compgen` when it is built with programmable completion, which the
  # non-interactive build (`--disable-readline`) turns off.
  buildInputs = [ bash ];

  dontConfigure = true;
  dontBuild = true;

  installPhase = ''
    runHook preInstall

    install -Dm755 vuh.sh "$out/bin/vuh"

    installShellCompletion --cmd vuh --bash vuh-completion.sh
    # installShellCompletion decides on the file name (`vuh` or `vuh.bash`
    # depending on the nixpkgs vintage); ask it rather than guess.
    bashCompletion=$(echo "$out"/share/bash-completion/completions/vuh*)

    # vuh ships no zsh completion; reuse the bash one through bashcompinit.
    substitute ${./vuh.zsh-completion.in} vuh-completion.zsh \
      --subst-var-by bashCompletion "$bashCompletion"
    installShellCompletion --cmd vuh --zsh vuh-completion.zsh

    # The templates users copy into their own projects as `.vuh`.
    install -Dm644 -t "$out/share/vuh/project-config-templates" project-config-templates/*

    # `vuh --configuration` prints this file. installer.sh generates it at
    # install time; here it is simply part of the (immutable) package.
    install -dm755 "$out/share/vuh"
    {
      echo "# configuration file path: $out/share/vuh/.installation_info"
      echo "# Generated by the Nix package: this installation is immutable, so"
      echo "# none of these locations can be changed after the fact."
      echo ""
      echo "INSTALLATION_DIR='$out/bin'"
      echo "COMPLETION_DIR='$(dirname "$bashCompletion")'"
      echo "COMPLETION_SCRIPT_NAME='$(basename "$bashCompletion")'"
      echo "DAILY_UPDATE_CHECKS='${lib.boolToString enableUpdateChecks}'"
    } > "$out/share/vuh/.installation_info"

    install -Dm644 -t "$out/share/doc/vuh" README.md LICENSE

    runHook postInstall
  '';

  # `--prefix` rather than `--suffix`: vuh parses the output of these tools, so
  # it should get the versions it was tested against. The caller's PATH is still
  # searched afterwards, which keeps git's own helpers (ssh, credential helpers,
  # gpg) working.
  postFixup = ''
    wrapProgram "$out/bin/vuh" \
      --prefix PATH : ${lib.makeBinPath runtimeInputs}
  '';

  passthru = {
    inherit enableUpdateChecks;

    tests = callPackage ../../tests { vuh = finalAttrs.finalPackage; };

    updateScript = nix-update-script { };
  };

  meta = {
    description = "Git-aware helper that reads, compares and bumps your project's semantic version";
    longDescription = ''
      vuh (version update helper) reads the version out of whatever file your
      project keeps it in, compares it with the version on the main branch and
      tells you — or writes for you — the version the current branch should
      carry. It is driven by a `.vuh` file in the repository root and understands
      mono repositories with per-module versions.

      This build is packaged for Nix: it never writes to its own installation
      directory, does not check for updates behind your back and cannot replace
      itself. Update it the way you installed it.
    '';
    homepage = "https://github.com/Greewil/version-update-helper";
    changelog = "https://github.com/Greewil/version-update-helper/releases/tag/v${finalAttrs.version}";
    license = lib.licenses.mit;
    mainProgram = "vuh";
    maintainers = [ ];
    platforms = lib.platforms.unix;
  };
})
